name: Update NSE Bhavcopy

on:
  schedule:
    - cron: "30 10 * * 1-5"   # runs every weekday at 10:30 AM IST
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run script
        run: python update_bhavcopy.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add eq_bhav.csv fo_bhav.csv
          git commit -m "Auto update bhavcopy"
          git push
